language: android
sudo: false
env:
  global:
  - secure: ez05MxuY/8K9UKtdM5IHpok+VsB8TNvj5Yr6QYZzAUZHgcjjrAtbnPUK0ZXOlLfNCgReNQ4rLtEwex4bRkfqhv0SferBgHTC6hOGMDPSXQJJB+zL+wvQB3EFy+br+c3B69/k+a8leSx44KHzRoK/3aBKCkIi1oNAkJ/nH879ibHEh9ndNe7pLxKLFZaq7P5dQJh59eCXPzuEwNU+XFmF08MRyIDk+eiY+F1EzVA1qrUS3YZrYxozsMO9Sas+Ocr6PswZGCGphU4uubwOYeOGEpcJu6Fm8lPdlivLgnhRYw+XeGC1X6c1/uHUb/g9OsIBzBb8mMnKxr/3JIp5M3RAPYmNW2TKWJXqVVCjClTStUjMKuy1VnYwEUwItoK0/LD2ZUiwvK2XhT2IMLIzg5kvVwkHEMRhlgfhjKz1541HAg8Fs8f0/7OP8rU9NPi2LY1AGwgLKN4lwlA0RgJofMqJs7Pv8bFOrI4XHk/b3fwEzlhGDTYBmy8yeMTvDDuDfs/v4fOBgAGIYM+OJihlOmDnDl68kAOQmFIBKZqxJ3imu9DPwxAIeRcqHN7GFzWlgA8CRxxJePFnSrUhvcQlMobdJWunYye0eRMkdDSPp/LmKNx568vs45C0K0hu0QcYFLeqXGUuDsZICEHLWOBxq1xH3KCvjsb208O3H30hFGSdtpU=
  - secure: UvRWdcmOat12AJVRrZtMp48FyzUCbnFQ3wGRjAV5AcbmzW+8AJ/Rs+SdoaqAWTepGz+09u2yOz85+fJOPDuXYZE78WgGtldoVVHHpeWDEcc7Kj9XUuqLsPUGZ6jW7LtUTom5IpCcDiwH/otXriH9avUXhG429IcJmpigus0TTb0B9hN0NPYCB1a3BzKsqAMFwlV+ewa3iQJYRLowkVc3W4rYllI7SEIBScrk1pYfBO9LFwOdlgsSmP1EGXRTO/Rlm+VqJOWh0IMMbfuOpVX6jP/zl1XlkrTz6BwOscgLtwWZycENcRShNMMsSUT1yR7r4/ugKHqok4ryzDHKDajXxbUpDCKuGA20flcwTllm51t+zPB0uIszE6cooUsVcWAQxu+2QYLTlR2V/f85P9T4T4rA+KtJWNDcdO7Fqr2S7DMqxHqMO1O3dGN80mmvrfzo4n7EeR1+/6zyNt8wVygzgLdMWvSFpK7dPboep4s/1Bync/gsLmj7BHeGIu3pXDBE5kHBtrxJNZr26z8nz+TCaDkB7vL+VhVeTgv74R3vcmJbrt+qZJkWqPkO1H9C7ZXFAEIZvPLEmO5+92HbKw+FE9+EWJz+jOfpLELohRg6c1s9u/4+Wqq3pM4Bgkwl1aS6bvpD8Kep+hOpDttz+rKJsE+I810254puJFw4BzcAeeY=
  - secure: HqwRAk+ZH6NAwRlqj6XaCJKqqbMWXbsgYyU8IyrN7zm2424ZaSnJfNnGEu3RphC9jIO+OINwIGim2J1JAVyhfEEUyXeqfA4ARWk9opqlLTsB45TXqmJFLyT9d5IASv7JDl+irW6YvkpxaW3v19DlaaFqvivREGjfIgKCqFoMM5nYsfD86ezthYAmtJElGPvW5PLOLUq/h2W93JmhYQc4mVECYyEc+S+w47RPErdWZUvl7Ea1XTZz/eEM7ScaRUsOeeL1x4bOa+Zv6Jku9n1rbt6SwVfCdDFcj0jugc+okG4ebhyRyRjrhq9DjAANzhceKvfPUJZCKPeIYYZ58NNp7M7SI6XGH7s6q21aWApazg2SDwcH062TyckBrIyp2byieUzRJJZr7p5xgNCcZTfqcpxSwu12s8OP/iCA7g1TrY4pAhu1EOwUVuvr2PExg/jCL583hF9YYsdFe7urPduPNV064T+EKhmNs1i/xFThZN6fdW4OpAL96+9ZZeuqJeE4ScYOTgWM02DCaRWkaFckHyFN7aN2a/CTwCDPGAE1opFqc5FasqATpPl2Hn95eAgyOmd8wersmJrK7kPPRBtcPJXO6e5NJ8JdePs89Wb8pqzg7R3+KXYU05wQ+W7COqK+UoaZBltk6+ZUz5w7rM0wXNetOT0+VrXSbjPRL6PEwxQ=
after_failure:
- cat sdkmanager.log
- cat emulator.log
- cat logcat.log
- cat build/tmp/linkSodiumjniSharedLibrary/output.txt
after_success:
- "./after-success.sh"
matrix:
  include:
  - os: linux
    services: docker
    script:
    - travis_retry docker build .
  - os: linux
    dist: trusty
    sudo: required
    before_script:
    - ". ./setenv.sh"
    before_install:
    - travis_retry travis_wait 120 ./dependencies.sh
    script:
    - travis_wait 120 ./travis.sh
  - os: osx
    osx_image: xcode9.2
    cache:
      ccache: true
      directories:
      - "$HOME/Library/Caches/Homebrew"
    before_script:
    - ". ./setenv.sh"
    before_install:
    - brew install ccache
    - travis_wait 120 ./dependencies.sh
    script:
    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    - travis_wait 120 ./travis.sh
